name: Main workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: chess


jobs:
  publish-docker:
    name: Publish Docker image
    runs-on: ubuntu-22.04
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main
    - name: Build image
      run: docker build -t $IMAGE_NAME .
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push image to Github Container Registry
      run: |
        IMAGE_USER=$(echo ${{ github.repository_owner }} | awk '{print tolower($0)}')
        docker tag $IMAGE_NAME ghcr.io/$IMAGE_USER/$IMAGE_NAME:${{ steps.package-version.outputs.current-version }}
        docker push ghcr.io/$IMAGE_USER/$IMAGE_NAME --all-tags