name: Develop workflow

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run jest tests
    runs-on: ubuntu-22.04
    steps:
    - name: Clone repo
      uses: actions/checkout@v3
    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Execute tests
      run: npm test